import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ countries }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next - GetServerSideProps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>All Countries</h1>
      {countries.map((country) => (
        <p key={country.name.common}>{country.name.common}</p>
      ))}
    </div>
  );
}

export const getServerSideProps = async () => {
  const countries = await fetch("https://restcountries.com/v3.1/all").then(
    (res) => res.json()
  );
  return {
    props: {
      countries,
    },
  };
};
